### ISSUE TITLE
make stepIncrement field obsolete and hide it

### ISSUE THREAD

**Issue by ZiwKerman** [erendrake/InfernalRobotics#10]
it was only used for speed tweaks, but now we use different UI for tweakable

**Comment by erendrake** [comment]
Duplicate is a stand in for redundant. Question is so we can have comments from others about this.

**Comment by pellinor0** [comment]
It is still used for the min/maxTweak tweakables. 

Of course that does not stop it from being ugly parsing code that needs to go. I just don't see a good solution yet.

**Comment by ZiwKerman** [comment]
I tried it yesterday and either we broke it, or they never affected minTweak/maxTweak

**Comment by pellinor0** [comment]
Done with pull request "stepIncrement cleanup"
