### ISSUE TITLE
solution for configureInterpolator

### ISSUE THREAD

**Issue by pellinor0** [erendrake/InfernalRobotics#11]
There are some servo values that may not be changed while moving, I would call them configuration values: 
* range (min/max)
* acceleration
* maxVelocity (more or less invisible at the moment anyway)
* isModulo (alias the limitTweakableFlag)

The current solution is to have the tweakable values different from the active values, and an event 'configureInterpolator' to set the active values (the event is ignored while moving). This is not optimal and may confuse people. 

An alternative would be to deactivate those tweakables while moving. This iss easy in the right click menu, I'm not sure how the UI window would feel about it. 

I think about those values as configuration data that you typically would calibrate when the vessel is built and not change in normal operation. So you would want a way to change them, but not necessarily on the main control panel.

**Comment by ZiwKerman** [comment]
This fields are not visible in Servo Control, and I can prohibit opening in-flight group editor in case at least one servo is moving.

**Comment by pellinor0** [comment]
You would also need to force-close the group editor if a servo starts moving, not sure if this is a good idea. 

An alternative is to pull the configuration every time a servo stops moving. This is already much better, just lacks some user feedbck if a change has alreadybeen set active or not.

**Comment by pellinor0** [comment]
Done. We now read configuration values whenever the interpolator is idle and a new command arrives. 

If a new limit would make the current position illegal we will only partly accept it (and try again next time, so it doesn't get lost). So if pos=2 and maxTweak=1, then the limit is set to 2.
