### ISSUE TITLE
Design simplistic UI for servo preset positions and movement between them

### ISSUE THREAD

**Issue by ZiwKerman** [erendrake/InfernalRobotics#13]
I have some ideas in mind on how to do it UI-wise, though I want to discuss persistence issue - where and how to store this information. 

First thing that comes to mind is adding a string persistent field and parse it in OnStart somewhere and make a simplistic UI to work with it.

How do you feel about it?

**Comment by pellinor0** [comment]
If you have per-servo information you could put it in the part module. 

For this UI you might want to wait for erendrake's command infrastructure, because what you want to save might exactly be one of his new commands.

**Comment by ZiwKerman** [comment]
Merged.
