### ISSUE TITLE
Default units

### ISSUE THREAD

**Issue by pellinor0** [erendrake/InfernalRobotics#17]
I was thinking about those default units. As I remember zodius put all sorts of odd speed numbers in the part configs so that the parts would take the same time to move their whole range. This is redundant information, and we should not require it. 

So, at least for translation, this sounds like it would be nice to display the range as 0-100% per default. Then we can set the default speed in (% of range)/s, and it would be the same for all parts. For the future, we could set the value from zodius' parts as default and you would only need a line in the part.cfg if you want something different. 

What do you think, does this make sense? In this case, would 'range' be the min/max from the part config or the tweaked range from the editor?

**Comment by ZiwKerman** [comment]
I tend to agree for translation - there is no easy way to measure distance in editor, so displaying translation length in meters, inches or whatever is kinda useless, so we can display 0-100% of range for translation easily.

On the other hand rotation is very different. If you can see angles, it helps a lot in determining starting position, so % of range for rotation is not the thing I want to see in editor.

**Comment by pellinor0** [comment]
I agree for rotation position, what about speed? As I understand zodius, he rotates a 180° hinge twice as fast as a 90° one. Would this be a good default behavior for all rotating things?

**Comment by StahnAileron** [comment]
Created an account to reply to this:

Wouldn't a simple Degrees per Second (Deg/Sec) speed be enough?

I suppose the other option would be seconds per full rotation (Sec/Rot).

The first would be fine control (individual movement control) while the second would be for easier syncing between parts (e.g. you can set it to 5 seconds for every part in a group; all parts would be completely sync'ed during the movement if they are simply used for min/max movements.)

Also, for the second option, it would still work if you decide to change the limit ranges of a part, so you don't have to fiddle with 2 settings to get one movement you want.

Maybe a tweakable toggle for speed control? (Spd Ctrl Mode = Unit/Time or Time/Move). It's that or showing both options simultaneously. Adjusting one will affect the other in real-time.

**Comment by erendrake** [comment]
This issue was moved to MagicSmokeIndustries/InfernalRobotics#6
