### ISSUE TITLE
check/test node sizes

### ISSUE THREAD

**Issue by pellinor0** [erendrake/InfernalRobotics#23]
The node sizes of the legacy parts seem very small to me, about one size smaller that what i would expect. For example, the 1.25m docking washer has a 0.625m node. 

Additionally I heard that IR parts have physics problems with large nodes (I suspect thas has to do with jerking them around, so large nodes might be fine with our version).

**Comment by ZiwKerman** [comment]
I think this one was fixed by latest PR #43
