### ISSUE TITLE
Create a thread on KSP Forums in Addons Development for pre-release

### ISSUE THREAD

**Issue by ZiwKerman** [erendrake/InfernalRobotics#33]
Post a pre-release version there and get some feedback from a wider test-base.

**Comment by pellinor0** [comment]
Good plan. When we are done with our own testing. 

I'd give it a new AVC version number each time we publish a recompiled dll. so users know which version to refer to. The version file of the old IR version still points to sirkut's github, so it will not see our version and nag prople to update.

**Comment by ZiwKerman** [comment]
Done!
