### ISSUE TITLE
suspicious code in onPartRemove

### ISSUE THREAD

**Issue by pellinor0** [erendrake/InfernalRobotics#45]
Test what happens with rotation onPartRemove. This piece of code just looks strange. It says 'prevent creep', and then takes the rotation value and does something with rotation+-1deg. I just can't see how there could come something useful out of that. 

What I'd expect to see some creep in the order of one degree, if the code actually gets called. Or that the code is not needed and can be removed.

**Comment by erendrake** [comment]
+1 it is scary code

**Comment by ZiwKerman** [comment]
I'll try removing it and test out how would it be without it.

**Comment by pellinor0** [comment]
The rotation itself seems ok, moving a part back to zero rotation on detaching. The strange part is the OffAxis exception and this +1/-1. I'd expect that we should not need to care about limits here because we already kept them when writing the rotation.

**Comment by ZiwKerman** [comment]
I never actually tried this off-axis part in real crafts, so I never had any problems from this code.
As it only affects 1 part, we may even leave it here for now.

**Comment by pellinor0** [comment]
It actually affects everyone BUT this one part. So possibly the Off-axis piece does not get reset like the others. That's also something to test.

**Comment by ZiwKerman** [comment]
should be alright with #50
