### ISSUE TITLE
Change the way the EC is consumed by robotic parts.

### ISSUE THREAD

**Issue by ZiwKerman** [erendrake/InfernalRobotics#79]
This is not for the upcoming release, but we should really look into how IR consumes EC

**Comment by ZiwKerman** [comment]
As an idea for future releases we may try to scale EC consumption with SQRT of servo speed over base/cfg speed, but then we would need to bring back EC consumption in UI somewhere.

**Comment by erendrake** [comment]
This issue was moved to MagicSmokeIndustries/InfernalRobotics#3
