### ISSUE TITLE
Build changelog for v0.20B

### ISSUE THREAD

**Issue by erendrake** [erendrake/InfernalRobotics#82]
Chris Woerz - Merge branch 'develop'
ZiwKerman - Dynamic EditorWindowWidth
ZiwKerman - Quick fix for rotate limits
Stepan Andreev - Merge pull request #21 from erendrake/invertaxis
Chris Woerz - restored merge fail
Chris Woerz - review comments
Chris Woerz - rotate and translate have classes just for them
Chris Woerz - more encapsulation
Chris Woerz - better wrapping
Chris Woerz - much flailing
Chris Woerz - ControlGUI no long knows about MuMechToggle
ZiwKerman - IPresetable extension first pass
ZiwKerman - Bugfixes in MechanismBase children
Stepan Andreev - Merge pull request #20 from erendrake/develop
Chris Woerz - merge
Chris Woerz - Merge remote-tracking branch 'ZiwKerman/develop' into develop
ZiwKerman - Rest/MoveToPreset working in Editor
Chris Woerz - added new Mechanism base class
Chris Woerz - review of texture loader
Chris Woerz - Merge remote-tracking branch 'ZiwKerman/develop' into develop
ZiwKerman - Minor fixes + a bit logging
ZiwKerman - Fixed Editor bug
ZiwKerman - Reverted to original logic, erendrake got it wrong
Stepan Andreev - Merge pull request #74 from ZiwKerman/develop
ZiwKerman - Fix NRE
Chris Woerz - Merge pull request #69 from ZiwKerman/develop
ZiwKerman - MoveCenter fixed
ZiwKerman - Typo2
ZiwKerman - Typo
ZiwKerman - Fix IMechanism implementations for MoveLeft/Right
ZiwKerman - Attempt at creating Wrapper for ServoController
ZiwKerman - Small fixes
Stepan Andreev - Merge pull request #19 from erendrake/develop
Chris Woerz - split interface from servo classes
Chris Woerz - moved control over to servo
Chris Woerz - merge
Chris Woerz - Merge remote-tracking branch 'ZiwKerman/controller' into develop
ZiwKerman - Actual TextureLoader
ZiwKerman - TextureLoader in InfernalRobotics.Utility
Chris Woerz - Merge branch 'maninthemiddle2' into develop
Chris Woerz - Merge branch 'maninthemiddle' into develop
ZiwKerman - Small fixes
ZiwKerman - Gotcha
ZiwKerman - Gotcha
ZiwKerman - Test
ZiwKerman - Test
ZiwKerman - Texture handling refactor
Chris Woerz - one type per file
Chris Woerz - a lot of typing, no idea if it works
Chris Woerz - changed a silly name
Chris Woerz - name is behind servo
Chris Woerz - Moved Man in the middle to its own folder
Chris Woerz - man in the middled mumechtoggle
Stepan Andreev - Merge pull request #17 from erendrake/develop
Stepan Andreev - Merge pull request #59 from pellinor0/develop
pellinor0 - disable tweakMin/Max for modulo axes, and some cleanup
pellinor0 - Interpolator: do not limit targetPos for modulo axes
ZiwKerman - MoveToPreset()
ZiwKerman - Forgot to fix PrevPreset
ZiwKerman - Preset fixes + Translator redundancy removed
ZiwKerman - Some additional checks
Stepan Andreev - Merge pull request #16 from erendrake/develop
Chris Woerz - Merge remote-tracking branch 'ZiwKerman/part-filtering' into develop
Chris Woerz - Merge remote-tracking branch 'ZiwKerman/develop' into develop
Chris Woerz - Merge remote-tracking branch 'pellinor0/develop' into develop
Chris Woerz - Merge remote-tracking branch 'pellinor0/develop'
ZiwKerman - Bugfix in tweakables display in flight
ZiwKerman - Bug fix
ZiwKerman - hasModel Field was never used
ZiwKerman - Small check to avoid unexplained behaviour
Stepan Andreev - Merge pull request #14 from erendrake/develop
pellinor0 - more translation/rotation refactoring
ZiwKerman - minor
ZiwKerman - Second pass
ZiwKerman - first pass
pellinor0 - move TPS scaletype to legacy parts (too specific to include in core package)

**Comment by erendrake** [comment]
From the PRs

* So much refactoring / Code Cleanup
* Remove SoundPitch and SoundVolume from GUI everywhere
* GUI Enhancements
* New Icons
* Presets/Actions
* New Tweakscale configs

**Comment by ZiwKerman** [comment]
I've updated the changelog

**Comment by erendrake** [comment]
0.20B CHANGELOG

    More Code Cleanup
    GUI Enhancements
        Custom category in Editor listing all robotic parts.
        Editor and Flight window width is scaled dynamically
        Editor window now has an option to revert servo to 0
        In Preset Editor added button to move servo to preset, works in flight too.
        Position and ranges for inverted axis parts are now shown correctly and in different style
    Some new icons
    New Tweakscale configs
    Some minor bugfixes
